### ISSUE TITLE
What's ur fav video game? And what subject do u like and least like?

### ISSUE THREAD

**Issue by JBYT27** [RayhanADev/ama#1]
title says all lol

**Comment by RayhanADev** [comment]
LOL!
Okay, **I can't pick ONE** video game, but if I had to **choose three** in any order:
1. **Rocket League**
2. **Overwatch**
3. **Minecraft**

What subject I like the least.... **probably Principles of Law**. I don't want to take that class so I'm going out of my way to avoid it, and Law for sure isn't my thing (rules are meant to be broken xD) so yeah, that's my least favorite!

**Comment by JBYT27** [comment]
Kewl! lol, I play overwatch as well! :D Luv ur thoughts about laws lol

**Comment by RayhanADev** [comment]
Hahaha xD
