### ISSUE TITLE
How did you get your Github Student Developer Pack?

### ISSUE THREAD

**Issue by IcingHackz** [RayhanADev/ama#10]
^^^

**Comment by RayhanADev** [comment]
Hi!

Go to [https://education.github.com/](https://education.github.com/), click the card that says Student Developer Pack, and then they'll guide you through verification. I usually takes around a month for them to verify accounts (so if you start now they might verify your account by summer).

Hope that helps :D.

**Comment by IcingHackz** [comment]
Yup! That helps! :D
