### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by tsunami-or-something** [RayhanADev/ama#12]
**very important question:**

what are the last 3 funny numbers on the back of your parents credit card

_this is a joke please dont give me the last 3 funny numbers on the back of your parents credit card_

![image](https://user-images.githubusercontent.com/73726677/118147195-946ffe80-b3cc-11eb-83da-c87bce18a842.png)

**Comment by RayhanADev** [comment]
Umm lets see...
\*picks up credit card\*

Its...4...2...and 0! :D

jkjk xD

**Comment by whippingdot** [comment]
EYYYYYYYYYYYYYYYYYYYYYYYY (i tried it out and it worked uwu)

**Comment by IcingHackz** [comment]
lmfao @RayhanADev

**Comment by IcingHackz** [comment]
also @tsunami-or-something i thought u were ded xD

**Comment by RayhanADev** [comment]
> also @tsunami-or-something i thought u were ded xD

well he went to in-person school so yeah he's practically ded xD

**Comment by IcingHackz** [comment]
oh rlly? lmfao

**Comment by iop3** [comment]
oh :(

**Comment by iop3** [comment]
oh :(
