### ISSUE TITLE
Why is your profile icon a Shiny Furret?

### ISSUE THREAD

**Issue by Time-dragon** [RayhanADev/ama#14]
**Question**: Why's your icon a Furret?

**Comment by RayhanADev** [comment]
Henlo @Time-dragon!
I chose a shiny Furret because I love Furrets! They are my favorite Pokemon (and they are also really good for designing things too). As for the reasoning to why it's shiny... ƪ(˘⌣˘)ʃ no clue I guess pink is more appealing lol!
