### ISSUE TITLE
what is your catchphrase 

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/ama#15]
**Question**: what’s your catchphrase?

---

**Comment by RayhanADev** [comment]
Heylo @darkdarcool!

Catchphrase :>?

I'm not some sort of superhero or something to cary around a catchphrase to whip at people xD. Truthfully I have no clue lol.

**Comment by darkdarcool** [comment]
What’s something you say often

**Comment by RayhanADev** [comment]
@darkdarcool idk I say *kewl!* way too often xD.

**Comment by darkdarcool** [comment]
do you say it like, _kewl!_, or, _cool!_?

**Comment by RayhanADev** [comment]
kewl! ofc

**Comment by darkdarcool** [comment]
kewl(i said it!), also is it possible for you to get on DarkCSS, I have a couple things I need help with.

**Comment by RayhanADev** [comment]
Sure

**Comment by darkdarcool** [comment]
k
