### ISSUE TITLE
ReplitAPI

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/ama#16]
Noticed you were making it in a **TON** of languages, and I was just wondering, would it be ok if I made one in go(lang), or rust? Just so I can get practice in languages that I'm learning! If not, I may just make it for myself, thanks!

**Comment by darkdarcool** [comment]
I think rust is best actually

**Comment by RayhanADev** [comment]
@darkdarcool heya!

I actually have Go and Rust tabled for our next phase of changes! If you're interested I can make you a team leader in either or when the next phase comes rolling out :)

**Comment by darkdarcool** [comment]
I may start on the layout of the code, not the code itself, can I inv you to the repl to talk more there?

**Comment by RayhanADev** [comment]
Sure, just out of curiousity have you written an libs for rust/used fetching with rust?

**Comment by darkdarcool** [comment]
Hmmm, a little bit, not much. But what I hear it's easy if you do it right. Lemme look it up and see what I can find.

**Comment by darkdarcool** [comment]
https://dev.to/hb/how-to-fetch-a-web-api-with-rust-1390

**Comment by darkdarcool** [comment]
I also invited you to the repl

**Comment by darkdarcool** [comment]
it's [here[(https://replit.com/@darkdarcool/VirtualBountifulAddon#.gitignore)

**Comment by darkdarcool** [comment]
hey ray? there are a couple things I need to ask you in rust replapi. if you can go to it, use the link in the comment above.
