### ISSUE TITLE
Blizzard Battletag?

### ISSUE THREAD

**Issue by JBYT27** [RayhanADev/ama#17]
**Question**: What's your Blizzard Battletag? Thanks!

---

**Comment by JBYT27** [comment]
Lol, ok. Uh, may I ask, what's your Overwatch username/tag then?
Thanks!

**Comment by RayhanADev** [comment]
Ataraxia :)

**Comment by JBYT27** [comment]
Okie! Noice name :D

**Comment by RayhanADev** [comment]
Thanks :D
