### ISSUE TITLE
is this going ending?

### ISSUE THREAD

**Issue by iop3** [RayhanADev/ama#18]
iop3 has a question for you. he asks when is this ama going to end or is it going to go on forever ~~until your account gets deleted~~

###### p.p.s. iop3 says he has no idea why he is talking in 3rd person.

**Comment by RayhanADev** [comment]
It's a forever deal :)

Thanks! #PrideMonth 🏳️‍🌈 

Lol xD

**Comment by iop3** [comment]
oh gotcha! :)
