### ISSUE TITLE
When did you start coding?

### ISSUE THREAD

**Issue by IcingHackz** [RayhanADev/ama#2]
^^^

**Comment by RayhanADev** [comment]
Hiya! 

I **started learning to code when I was 7-ish** on the **Khan Academy course for Javascript** and then I **worked on my coding on and off up until mid-June of last year**. At that point I **hopped on a grind **and my learning curve shot straight up. I was **learning NodeJS, CSS, HTML, Python** and tons of other frameworks and modules and et cetera until I am where I am today!

**Comment by IcingHackz** [comment]
claP cLap 👏! Thx for answering my question! :D I started when I was 9 or 10-ish.

**Comment by RayhanADev** [comment]
Nice!
