### ISSUE TITLE
programming question...

### ISSUE THREAD

**Issue by iop3** [RayhanADev/ama#21]
This question requires you to have some knowledge of html.
> ~~you do have the knowledge right?~~

So the question is how do you like remove the `.html` from links. Like if you link to a file (let's say the file name is e.html) and it shows up like `example.com/e.html`, i want it to be `example.com/e`. Is there any way to do that? Thanks!

**Comment by RayhanADev** [comment]
@iop3 hihi!

Yeah I know HTML xD. I assume you use Replit's HTML, CSS, & JS environment :>? In that case instead of doing `e.html` create a folder with the name `e` and put an `index.html` file inside the folder :).

**Comment by iop3** [comment]
ah! Thanks!

**Comment by iop3** [comment]
ik i can use replit and do it but is there any way to do it in github? (github pages?)

**Comment by RayhanADev** [comment]
I believe it's the same :)

**Comment by RayhanADev** [comment]
It is an Internet standard after all.

**Comment by iop3** [comment]
lol ok
