### ISSUE TITLE
When did you start coding (Age)?

### ISSUE THREAD

**Issue by YEETEDWIN** [RayhanADev/ama#22]
**Question**: When did you start coding (Age)?

---

**Topics/Tags**:
#Age
#Compare

**Comment by RayhanADev** [comment]
Heya!

Around 7, I used a lot of Khan Academy to learn and then I started again recently doing some real stuff like servers, backend, and games :).

**Comment by TheQuackyDuck** [comment]
#2 lul

**Comment by RayhanADev** [comment]
> #2 lul

True dat lol.
