### ISSUE TITLE
Moving to a new house?

### ISSUE THREAD

**Issue by whippingdot** [RayhanADev/ama#23]
WHAT IS YOUR ADDRESS. GIVE IT TO ME RIGHT NOW OR YOU ARE DEAD

jk lol that was very bad of me, sorry

Anyway, the question was - are you a rich kid moving to a new house. I know this is a dumb question, but are you moving to a HUGE house or a normal-sized one with two floors?

Also, how are you doing, we haven't talked in some time... Maybe keep this issue open so we can just talk to each other and keep in touch?

Also, why don't you enable Discussions, convert all the issues into discussions, and disable issues? Discussions are more useful than issues for AMA I feel, as issues are issues so...

---

\#house \#wealthy \#friend

**Comment by TheQuackyDuck** [comment]
> are you a rich kid moving to a new house. 

not that polite but ok 😑

**Comment by TheQuackyDuck** [comment]
and rayhan will most likely reply to you AFTER he moved to the new house lul

**Comment by whippingdot** [comment]
> that's rough buddy

LOL

> not that polite but ok 😑

I know, that is my life now 😭

**Comment by darkdarcool** [comment]
LOL, I’m moving in like a month

**Comment by Tr1angular** [comment]
Oh child

**Comment by TheQuackyDuck** [comment]
> > that's rough buddy
> 
> LOL
> 
> > not that polite but ok 😑
> 
> I know, that is my life now 😭

xP

> LOL, I’m moving in like a month

:)

> Oh children

...?

**Comment by darkdarcool** [comment]
yea that confused me

**Comment by whippingdot** [comment]
Bruh @Tr1angular why are you watching this repo?

And he called us children

BLOCK HIM EVERYONE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

~~totally not an advertisement but https://github.com/Repl-it-Coders/Repl-it-Coders/discussions/28~~

**Comment by TheQuackyDuck** [comment]
hahahhahahha advertisement

**Comment by RayhanADev** [comment]
> Off-Topic but my gosh if whippingdot starts an issue it seems the entirety of the Replit Org follows xD.

Hi dude!

> are you a rich kid moving to a new house

We're temporarily downsizing to a nice little house near Westlake, TX. Kinda on the borderline of high middle class and middle middle class? I don't really care much about socioeconomial status to know lol. The move is mostly because I managed to skirt by my school remotely, but with the way things are going they'll be having us come to school soon and driving an hour every morning is not convenient. We are building (another) house which we'll move into by next year.

> Maybe keep this issue open so we can just talk to each other

I'll start a discussion for random things so we can talk there!

> Also, why don't you enable Discussions

Discussions ain't my thing lol. I like this issues layout.

---

> and rayhan will most likely reply to you AFTER he moved to the new house lul

Completely and entirely accurate xD. We just finished setting up the media room so now the PCs, TVs, and consoles are all in! Back to coding :D.

**Comment by TheQuackyDuck** [comment]
ooooo, im the first person to see rayhanadev's reply :o.



> > Off-Topic but my gosh if whippingdot starts an issue it seems the entirety of the Replit Org follows xD.
> 
> Hi dude!
> 
> > are you a rich kid moving to a new house
> 
> @whippingdot
> 
> We're temporarily downsizing to a nice little house near Westlake, TX. Kinda on the borderline of high middle class and middle middle class? I don't really care much about socioeconomial status to know lol. The move is mostly because I managed to skirt by my school remotely, but with the way things are going they'll be having us come to school soon and driving an hour every morning is not convenient. We are building (another) house which we'll move into by next year.
> 
> > Maybe keep this issue open so we can just talk to each other
> 
> @whippingdot
> 
> I'll start a discussion for random things so we can talk there!
> 
> > Also, why don't you enable Discussions
> 
> @whippingdot
> 
> Discussions ain't my thing lol. I like this issues layout.
> 
> > not that polite but ok 😑
> 
> Yeah true @whippingdot you shouldn't ask about people's socioeconomial status.
> 
> > and rayhan will most likely reply to you AFTER he moved to the new house lul
> 
> @TheQuackyDuck
> 
> Completely and entirely accurate xD. We just finished setting up the media room so now the PCs, TVs, and consoles are all in! Back to coding :D.
> 
> > LOL, I’m moving in like a month
> 
> @whippingdot
> 
> Oh nice! You told me about that too.

nice! 🙂

**Comment by TheQuackyDuck** [comment]
also i've been living in my house for at least my entire life lol

**Comment by whippingdot** [comment]
> Yeah true @whippingdot you shouldn't ask about people's socioeconomial status.

😞 

> I'll start a discussion for random things so we can talk there!

issue or discussion?

> > LOL, I’m moving in like a month

> @whippingdot

> Oh nice! You told me about that too.

I think you meant to reply to @darkdarcool 

> We're temporarily downsizing to a nice little house near Westlake, TX. Kinda on the borderline of high middle class and middle middle class? I don't really care much about socioeconomial status to know lol. The move is mostly because I managed to skirt by my school remotely, but with the way things are going they'll be having us come to school soon and driving an hour every morning is not convenient. We are building (another) house which we'll move into by next year.

kk ~~ANOTHER HOUSE~~ just kidding good for you. Sorry for the question if it offended you, it was meant as a joke but you answered so 🤷. I even live in a pretty big house (I wasn't going to say that but you replied so...). I won't tell you what or where though for privacy reasons. Also, I don't care about your 'socioeconmical' status, I just asked. I don't care if you are rich or not.

Oh, and why did you say where your house is? Maybe edit it and delete that for privacy reasons...

> We just finished setting up the media room so now the PCs, TVs, and consoles are all in!

Media room...Is that like a home theatre? Cause I have that. The only thing is our PCs are just set up randomly, and they aren't in a specific room. I do have a console in the home theatre though...

Do you play Xbox or PS5 BTW? I play on an Xbox, but I am planning to move to PC this birthday. Most 'professional gamers use PC so ima buy Minecraft java and test it out on my laptop this birthday.

A few last questions, don't reply if you don't want to, but:
- Do you prefer Windows or Mac
- What company laptops / PCs do you buy (i have a lenovo laptop but i didn't choose)
- And do you have a PC or a Laptop
- Are you hyped for Windows 11 (my dad has it on his computer cause he works at Microsoft)

**Comment by TheQuackyDuck** [comment]
> - Do you prefer Windows or Mac
> - What company laptops / PCs do you buy (i have a lenovo laptop but i didn't choose)
> - And do you have a PC or a Laptop
> - Are you hyped for Windows 11 (my dad has it on his computer cause he works at Microsoft)

ik that rayhan should answer this but imma answer it too.

1. Windows (pogers)
2. well im not sure...
3. what is the difference?
4. yesssssss (my mom used to work at microsoft)

**Comment by JDOG787** [comment]
I have one thing to say - windows is kinda meh

**Comment by darkdarcool** [comment]
Yea, I’m a Mac boi

**Comment by RayhanADev** [comment]
Linux goes brrrrr but I use Windows at school and iPadOS on my iPad so um... no preference?

**Comment by JDOG787** [comment]
I use mac and linux

**Comment by whippingdot** [comment]
awww...well mac is preferred for coders but my dad works at Microsoft so i kinda have to use windows. I do prefer windows though...just apple is better for the 'ecosystem' thing.

At least @JDOG787 are you hyped for windows 11? If you don't know what that is, go to the official windows youtube channel and watch the 1 minute recap of the event or something like that. It looks kinda like mac for you guys, and its desktop feature is way more improved from before. Centered taskbar, and more stuff like they didn't show but i can tell you like a redesigned settings, etc.

@darkdarcool well try out windows, or at least watch that youtube channel 1 minute or 10 minute recap

@RayhanADev Cool cool. Do you have an iPhone? Or have your parents not allowed you yet ~~like me~~. Also, did you see the iPadOS recap for the apple event? WIDGETS ARE EVERYWHERE and we get the app library, kinda useless, but 🤷 . Also wdym by Linux goes brrrrr? You use Linux for personal or wut?

~~i am happy schools force kids to use windows because they are poor and can't afford macs 😈~~

Also, can you respond to the full message?

@TheQuackyDuck EYYYYY ~~me and you are lonely moi friend~~

**Comment by TheQuackyDuck** [comment]
> @TheQuackyDuck EYYYYY me and you are lonely moi friend

meaning...?

**Comment by whippingdot** [comment]
we are the only windows

**Comment by JDOG787** [comment]
> At least @JDOG787 are you hyped for windows 11? If you don't know what that is, go to the official windows youtube channel and watch the 1 minute recap of the event or something like that. It looks kinda like mac for you guys, and its desktop feature is way more improved from before. Centered taskbar, and more stuff like they didn't show but i can tell you like a redesigned settings, etc.

nah, I don't see much difference and I don't even use Windows anyways.

**Comment by TheQuackyDuck** [comment]
> we are the only windows

ah, i see

**Comment by whippingdot** [comment]
why you know respond two meh? it ok bai bai
