### ISSUE TITLE
Would you like to do a project together?

### ISSUE THREAD

**Issue by BD103** [RayhanADev/ama#24]
**Question**: Hi! Would you like to code a project together?

We've been out of touch for a while now, and I had a brilliant idea. It all happened when I was checking out [GIthub's Design System](https://primer.style/) when I found their CSS framework. After some playing around, I thought this:

What if we recreated a Github-like website using the API and some integration, but used a different CSS framework? I played around with some different ones, like Bootstrap and Bulma before I came across [UIkit](https://github.com/uikit/uikit). The plan is that I work on the design and front-end of the website, while you handle the backend with all of Github's API. I don't really mind what language we use, as long as I can design HTML files and use Sass/Less. (So Node is perfectly fine, though Python works too!)

Sorry for the word wall, and I can't wait to see what you say!

-BD103 :P

(P.S. what's your phone number lol)

**Comment by whippingdot** [comment]
Bruh why the phone number ask we all kids and that seems kinda weird

also can i join in i have not talked to you for a LONG time BD (since you left the org which is now ded)

Also basically you wanna recreate GitHub's CSS using a different CSS framework right? What are they using rn

Also i am very under-developed in CSS frameworks sry

**Comment by RayhanADev** [comment]
@BD103 hiiii! Glad you still remember me xD.

I really want to work on a project with you *but* I have commitments to school (and likely a job) after coming back in-person D:

If you want to work on something, my next vacation (when I can commit to something with you guys) is Nov. 19th and I would love to do something then!

---

Alternatively, I can hop onto a Repl when I have free time and do a bit of programming--typically early in the morning and for a few minutes. I can certainly come up with the backend then if you have a good idea of what you want to do!

\~ Ray :D

Also I don't share my number on the Internets unless I need to :P

**Comment by BD103** [comment]
Ok! Glad to see so much interest in this project. Let me answer a few things...

> Also basically you wanna recreate GitHub's CSS using a different CSS framework right? What are they using rn

Github's current CSS framework and design system is [primer.style](https://primer.style/). An example of what I'm trying to do is [here](https://gudhub.bd103.repl.co/). I want to give this website baseline functionality. There will be no authentication and no personalized content. I want to recreate the website as if you are not logged in.

(Though the home page actually shows what would be if you were signed in, so ignore that lol)

> Bruh why the phone number ask we all kids and that seems kinda weird

(It's a joke lol)

> If you want to work on something, my next vacation (when I can commit to something with you guys) is Nov. 19th and I would love to do something then!

That sounds good! @whippingdot and I will start working on the project, then we can send you it after we get a bit of it done.

> Alternatively, I can hop onto a Repl when I have free time and do a bit of programming--typically early in the morning and for a few minutes. I can certainly come up with the backend then if you have a good idea of what you want to do!

We'll invite you to the repo if you want to check it out, but no worries!

**Comment by BD103** [comment]
Also, think about what language we are programming this in

**Comment by whippingdot** [comment]
> That sounds good! @whippingdot and I will start working on the project, then we can send you it after we get a bit of it done.

to be true, just like all the projects we did on the org, most projects die out in a week or two. So me and BD will probably start the project, let it die it out, maybe come back in October, and basically do little progress. When you come back in November I think we can take the project full scale

> Also, think about what language we are programming this in

Umm node is the best for me cause i don't know the python one (i forgot the name django or smthing)

> (It's a joke lol)

Unfortunately no one got it lol

Also, where do you live BD (like not exact location, country. don't tell that either if you don't want to say)? It seems kinda weird that you would be messaging in the middle of the night in USA (I come from Washington so I assume it is midnight around 4:30 AM)

**Comment by whippingdot** [comment]
P.S. My computer be lagging a lot but in my task manager nothing seems too much...any suggestions?

**Comment by BD103** [comment]
> P.S. My computer be lagging a lot but in my task manager nothing seems too much...any suggestions?

Close windows, restart, do any software updates, clean up storage, etc.

I live on the eastern coast of America, so EST

**Comment by whippingdot** [comment]
yea i restarted cause my dad said the same thing

wait lemme search up EST time rn
