### ISSUE TITLE
Tip

### ISSUE THREAD

**Issue by coolcoder-js** [RayhanADev/ama#8]
You can also use the `discussions` tab instead of `issues` for Ask Me Anything.

**Comment by RayhanADev** [comment]
Heylo!

True, true I prefer issues however because issue templates make life easier :D.

**Comment by IcingHackz** [comment]
i don't see the `discussions` tab in this repo. 🤔

**Comment by RayhanADev** [comment]
I removed it when I made the repository.

**Comment by IcingHackz** [comment]
oh xD  kk

**Comment by coolcoder-js** [comment]
Yeah, if you go to `settings` and scroll down, you will see an `open discussions` option.
You have to turn that on and edit the template to make a new template.
